import type { Metadata } from "next";
import { Inter, Comfortaa, Coiny } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./Components/Footer";
import Header from "./Components/Header";
import StoreProvider from "./redux/provider";

// const inter = Inter({ subsets: ["latin"] });
const comfortaa = Comfortaa({
  subsets: ["cyrillic"],
  variable: "--font-comfortaa",
});
const coinyCirillic = localFont({
  src: "./fonts/coinycyrillic.woff2",
  variable: "--font-coinyCirilic",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" className="h-full" style={{ scrollBehavior: "smooth" }}>
        <body
          className={`${comfortaa.className} overflow-x-hidden ${comfortaa.variable} ${coinyCirillic.variable} h-full `}
        >
          <div className="flex flex-col h-full">
            <Header />
            <main className="pt-[64px] flex-[1_0_auto]">{children}</main>
            <Footer />
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
